; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1






;things need to be done
; fix loading time tester with message box
; fix new line text file problem








if !(A_IsUnicode=1 and A_PtrSize=4)
{
    SplitPath, A_AhkPath, , dir
    Run, %dir%\AutoHotkeyU32.exe "%A_ScriptFullPath%"		
    ExitApp
}
hSkinH := DllCall("LoadLibrary", "Str", "SkinHu.dll")
DllCall("SkinHu\SkinH_AttachEx", "Str", A_ScriptDir "\skins\0021.she")
;If (Gameexe !="")
;    SelectedGame := Gameexe
;Else
;    SelectedGame := "Selected Game"
Logdir := A_AppDataCommon "\GameslistGeo11"
FileCreateDir, %Logdir%
LogGames := A_AppDataCommon "\GameslistGeo11\Gamename.txt" 
ColumnNr := [1]
delimiter := ","
Loop, read, %LogGames%
{ 
    Cell := StrSplit(A_LoopReadLine,delimiter)
    Stored := Cell[2] "|" Stored
}

Imagine := A_ScriptDir "\ico\bg.jpg"
Gui, Add, Picture, x-8 y0 w610 h385 , % Imagine

Gui Font, s9, Segoe UI
Gui Add, DropDownList, vVersion x288 y72 w84, x64 game||x32 game
Gui Add, Text, x192 y16 w189 h61, Select Game Location and version,`n'Generate' will push the Geo11 files and a Geo11 desktop shortcut.
Gui Add, Button, gGenerate x288 y112 w84 h23, Generate
Gui Add, Button, gBrowse x184 y72 w85 h23, Browse
Gui Add, Button, gUninstall x288 y248 w84 h23, Uninstall
Gui Add, ListBox, vStoredforDisplay x176 y176 w102 h95, %Stored%

Gui Add, Text, x179 y143 w101 h23, Current Installs
Gui Add, Text, x176 y168 w120 h23, %Gamename%
Gui Add, Text, x8 y8 w154 h278, This app will take the Geo11 files such as dxd11.dll and move to a "geo" folder. `n`nIt creates a desktop shortcut, when clicked, it will move the game's original "dxd11.dll" files to "/originaldx" and load geo11 dxd11 files. Creating a VR specific launcher/shortcut.`n`nOn game close, the files will return to original locations. 
;Gui Add, Edit, x184 y216 w85 h23, %SelectedGame%
Gui Show, w390 h295, Mod Manager for Geo11 
Return

Browse:
    {
        FileSelectFile, Selectgame, 32, , Select a game, Application (*.exe); *.lnk
        if (Selectgame = "")
            MsgBox, You didn't select anything.
        else
        {
            SplitPath, Selectgame, Gameexe, Gamepath, Gameextenstion, Gamenameonly
            Loop, read, %LogGames%
            { 
                Currentline := A_LoopReadLine
                If InStr(Currentline, Gamenameonly)
                {
                    LineRead := StrSplit(Currentline,delimiter)
                    Gamename := LineRead[2]
                    Msgbox, Error. %Gamename% already has Geo11.
                    GameError := 1
                    break
                }
                Else
                    GameError := 0
                Return
                ;Gui Add, ComboBox, vcbx w200 vVersChoice, x32||x64 
            }
        }
    }

            Generate:
                {
                    if (GameError=0)
{
                    GuiControlGet,VersionRet,, Version
                    Msgbox, %VersionRet% Dlls for %Gameexe%
                        if (VersionRet="x64 game")
                    {
                        64or32 := "\Geo3dFilesGoHere\x64\"
                    }
                    Else
                    {
                        64or32 := "\Geo3dFilesGoHere\x32\"
                    }
                    DllLocal := A_ScriptDir 64or32
                    ChangeNames := DllLocal 

                    ;arraygeo := ["d3d11.geo", "d3dcompiler_47.geo", "d3dx.geo", "d3dxdm.geo", "nvapi64.geo"]
                    arraydll := ["d3d11.dll", "d3dcompiler_47.dll", "d3dx.ini", "d3dxdm.ini", "nvapi64.dll"]
                    FileCreateDir, %Gamepath%\geo
                    For index, value in arraydll
                    { 
                        geo := % arraydll[index] 
                        FileCopy, %DllLocal%\%geo%, %Gamepath%\geo\%geo%, 1
                    }
                    FileCopy, %A_ScriptDir%\leaveingamedir.exe, %Gamepath%\leaveingamedir.exe, 1
                    FileCopyDir, %DllLocal%\ShaderFixes, %Gamepath%\ShaderFixes, 1

                    Logfile := Gamepath "\Gamename.txt"
                    Random, rand, 1, 12
                    Localicon := A_ScriptDir "\ico\" rand ".ico" 
                    TextforGamelog := Selectgame "," Gameexe
                    FileDelete, %Logfile% ; 
                    FileAppend, %Selectgame%, %Logfile% 
                    FileAppend, %TextforGamelog%, %LogGames%
                    msgbox, %TextforGamelog%

                    ShortcutMaker := A_Desktop "\" Gamenameonly " VR.lnk"
                    AHKLocal := Gamepath "\leaveingamedir.exe" 
                    FileCreateShortcut, %AHKLocal%, %ShortcutMaker%, %Gamepath%,,,%Localicon%
                    Msgbox, Geo11 Shortcut sent to desktop. 
}
Else

                }
            return

            Uninstall: 
                {
                    GuiControlGet, StoredGet,,StoredforDisplay
                    Msgbox, %StoredGet%
                    delimiter := ","
                    Loop, read, %LogGames%
                    { 
                        Currentline := A_LoopReadLine
                        If InStr(Currentline, StoredGet)
                        {
                            LineRead := StrSplit(Currentline,delimiter)
                            GameLocation := LineRead[1]
                            SplitPath, GameLocation, OutFileName, OutDir, OutExtension, OutNameNoExt, OutDrive
                            Filedelete, %GameLocation%\geo\*.dll
                            Filedelete, %GameLocation%\leaveingame*.exe
                            Msgbox, Success
                        }

                    }
                    return
                }

                ;geo3d:
                ;    {
                ;        FileSelectFolder, OutputVar [, *StartingFolder, 2, Select where you will store], Selectgeo, 32, , Select D3Directory, File (*.dll); *.lnk
                ;        if (Selectgeo = "")
                ;            MsgBox, The user didn't select anything.
                ;        else
                ;        {
                ;            SplitPath, Selectgeo, Geoexe, Geopath, Geoextenstion, Geonameonly
                ;        }
                ;    }
                ;return
                ;
                ;generate:
                ;{
                ;        loglocal := "\Logfile.txt"
                ;        Logfile := A_AppDataCommon loglocal
                ;        }
            GuiEscape:
            GuiClose:
            ExitApp