; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

;If (Gameexe !="")
;    SelectedGame := Gameexe
;Else
;    SelectedGame := "Selected Game"
Gui Font, s9, Segoe UI
Gui Add, DropDownList, vVersion x288 y112 w84, x64 game||x32 game
Gui Add, Text, x192 y16 w169 h41, Select Game Location,`nSelect x64 or x32
Gui Add, Button, gGenerate x288 y216 w84 h23, Generate
Gui Add, Button, gBrowse x184 y112 w85 h23, Browse
Gui Add, Text, x176 y168 w120 h23, %Gamename%
Gui Add, Text, x8 y8 w154 h278, This app will take the Geo11 files such as dxd11.dll and rename them to "dxd11.geo". `n`nIt creates a desktop shortcut, when clicked, it will rename the game's original "dxd11.dll" files to ".org" and rename the ".geo" files to ".dll". Creating a VR specific launcher/shortcut.`n`nOn game close, the files will return to original name
;Gui Add, Edit, x184 y216 w85 h23, %SelectedGame%
Gui Show, w390 h295, Mod Manager for Geo11 
Return

Browse:
    {
        FileSelectFile, Selectgame, 32, , Select a game, Application (*.exe); *.lnk
        if (Selectgame = "")
            MsgBox, You didn't select anything.
        else
        {
            SplitPath, Selectgame, Gameexe, Gamepath, Gameextenstion, Gamenameonly
        }
        Return
        ;Gui Add, ComboBox, vcbx w200 vVersChoice, x32||x64 
    }

Generate:
    {
        GuiControlGet,VersionRet,, Version
        Msgbox, %VersionRet%  Dlls for %Gameexe%
        if (VersionRet="x64 game")
        {
            64or32 := "\Geo3dFilesGoHere\x64\"
        }
        Else
        {
            64or32 := "\Geo3dFilesGoHere\x32\"
        }
        DllLocal := A_ScriptDir 64or32
        ChangeNames := DllLocal 

        arraygeo := ["d3d11.geo", "d3dcompiler_47.geo", "d3dx.geo", "d3dxdm.geo", "nvapi64.geo"]
        arraydll := ["d3d11.dll", "d3dcompiler_47.dll", "d3dx.ini", "d3dxdm.ini", "nvapi64.dll"]

        For index, value in arraydll
        { 
            val := % value 
            geo := % arraygeo[index] 
            FileCopy, %DllLocal%\%val%, %DllLocal%\geo\, 1
            sleep, 15
            FileMove, %DllLocal%\geo\%val%, %DllLocal%\geo\%geo%, 1
            sleep, 10 
        } 
        For index, value in arraygeo
        { 
            geo := % arraygeo[index] 
            FileCopy, %DllLocal%\geo\%geo%, %Gamepath%, 1
        }
        FileCopy, %A_ScriptDir%\VRLauncher.exe, %Gamepath%\VRLauncher.exe, 1
        FileCopyDir, %DllLocal%\ShaderFixes, %Gamepath%\ShaderFixes, 1

        Logfile := Gamepath "\Gamename.txt"
        Random, rand, 1, 12
        Localicon := A_ScriptDir "\ico\" rand ".ico" 
        FileDelete, %Logfile% ; 
        FileAppend, %Selectgame%, %Logfile%
        ShortcutMaker := A_Desktop "\" Gamenameonly " VR.lnk"
        AHKLocal := Gamepath "\VRLauncher.exe" 
        FileCreateShortcut, %AHKLocal%, %ShortcutMaker%, %Gamepath%,,,%Localicon%
    }

    ;geo3d:
    ;    {
    ;        FileSelectFolder, OutputVar [, *StartingFolder, 2, Select where you will store], Selectgeo, 32, , Select D3Directory, File (*.dll); *.lnk
    ;        if (Selectgeo = "")
    ;            MsgBox, The user didn't select anything.
    ;        else
    ;        {
    ;            SplitPath, Selectgeo, Geoexe, Geopath, Geoextenstion, Geonameonly
    ;        }
    ;    }
    ;return
    ;
    ;generate:
    ;{
    ;        loglocal := "\Logfile.txt"
    ;        Logfile := A_AppDataCommon loglocal
    ;        }
GuiEscape:
GuiClose:
ExitApp