; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1
; Include the Neutron library
#Include Neutron.ahk
#Include, %A_ScriptDir%\tf.ahk 
Logdir := A_AppDataCommon "\GameslistGeo11"
FileCreateDir, %Logdir%
LogGames := A_AppDataCommon "\GameslistGeo11\Gamename.txt" 
NextInstall := A_AppDataCommon "\GameslistGeo11\NextInstall.txt" 
GamesUpdate := A_AppDataCommon "\GameslistGeo11\GamesUpdate.txt" 
Helix := A_AppDataCommon "\GameslistGeo11\HelixLocal.txt" 
; Create a new NeutronWindow and navigate to our HTML page
You=  
(
<option value="64x">Virtual Desktop</option>
)
Fuck := You
Fuck= 
(
<option value="64x">Fuckme</option>
)

msgbox, %Fuck%
Simple := A_ScriptDir "\Simple.Html"
LineNumbers = % TF_Find(Simple,22,89,You) ;
msgbox, %LineNumbers%
;TF_InsertLine(Text, StartLine = 1, Endline = 0, InsertText = "")
LineNumbers := LineNumbers +1
Endliner := LineNumbers + 10
Msgbox, %Endliner%
;;Purpose: Insert text in specified lines
;Parameters: Text, StartLine, Endline, InsertText
TF_InsertLine(Simple,LineNumbers,Endliner,Fuck)     
; insert --- in lines 2 4 and 9. 5 is endline will be ignored

