; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

FileInstall, TA31-D-100549_RedChevron.jpg,TA31-D-100549_RedChevron.jpg
Zipfile := A_AppDataCommon "\GameslistGeo11\ziplocation.txt"
Gui Add, Picture, x0 y-32 w249 h285, TA31-D-100549_RedChevron.jpg
Gui Add, Button, gOkay x192 y224 w80 h23, Confirm
Gui Add, Button, gCan x280 y224 w82 h23, Cancel
Gui Add, Text, x16 y8 w223 h23 +0x200, Drag your custom shader's ZIP file here.




Gui Show, w378 h269, Drag and Drop Shader
Return

GuiDropFiles(GuiHwnd, FileArray, CtrlHwnd, X, Y)
{
    for i, file in FileArray
    {
        MsgBox Selected:`n%file%`nExtracting takes time, be patient. 
        global stored := file
        break
    }
}
return

Okay:
{
    FileDelete, %Zipfile%
    FileAppend, %stored%, %Zipfile%
ExitApp
}

Can:
GuiEscape:
GuiClose:
    ExitApp
